apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gateway
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: gateway
    spec:
      containers:
        - image: cheemsenjoyer/devops-gateway:latest
          name: gateway
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: ADD_SERVICE_HOST
              value: "add-service"
            - name: ADD_SERVICE_PORT
              value: "8001"
            - name: DIVIDE_SERVICE_HOST
              value: "divide-service"
            - name: DIVIDE_SERVICE_PORT
              value: "8004"
            - name: MULTIPLY_SERVICE_HOST
              value: "multiply-service"
              value: "8003"
            - name: SUBTRACT_SERVICE_HOST
              value: "subtract-service"
              value: "8002"
      restartPolicy: Always