apiVersion: v1
data:
  nginx.conf: |-
    worker_processes 1;

    events { worker_connections 1024; }

    http {
        upstream gateway-backend {
            server gateway:8080;
        }

        server {
            listen 80;

            client_max_body_size 10M;
            proxy_read_timeout 90;
            proxy_connect_timeout 90;

            location / {
                proxy_pass http://gateway-backend;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_redirect off;
            }
        }
    }
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: nginx
  name: nginx-cm0
